# Generated by Django 4.2 on 2024-05-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_productostalles_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productostalles',
            old_name='productos',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='productostalles',
            old_name='talles',
            new_name='id_talle',
        ),
    ]
