# Generated by Django 4.2 on 2024-06-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_productos_productostalles_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostalles',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='web.productos'),
        ),
    ]
