# Generated by Django 4.2 on 2024-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_productostalles_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallespedido',
            old_name='pedidos',
            new_name='id_pedido',
        ),
        migrations.RenameField(
            model_name='detallespedido',
            old_name='productos',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='detallespedido',
            old_name='talles',
            new_name='id_talle',
        ),
        migrations.RenameField(
            model_name='formasdepagopedidos',
            old_name='formasdepago',
            new_name='id_forma_de_pago',
        ),
        migrations.RenameField(
            model_name='formasdepagopedidos',
            old_name='pedidos',
            new_name='id_pedido',
        ),
        migrations.RenameField(
            model_name='formasdepagopedidos',
            old_name='tarjeta',
            new_name='id_tarjeta',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='usuarios',
            new_name='id_usuario',
        ),
    ]
