# Generated by Django 4.2 on 2024-06-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_pedidos_detallespedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallespedido',
            name='id_pedido',
            field=models.ForeignKey(db_column='ID_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.pedidos'),
        ),
        migrations.AlterField(
            model_name='formasdepagopedidos',
            name='id_pedido',
            field=models.ForeignKey(db_column='ID_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='forma_de_pago', to='web.pedidos'),
        ),
    ]
